version: '3.9'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: alma
            POSTGRES_PASSWORD: almapassword
            POSTGRES_DB: alma
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

    redis:
        image: redis:6.2-alpine
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/var/lib/redis/data

    server:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: server
        environment:
            ALMA_REDIS_URL: redis://redis:6379
            ALMA_DATABASE_URL: postgresql://alma:almapassword@postgres:5432/alma
            ALMA_SESSION_SECRET: gjnkdA2/a43fs%1Sdmasjkq299
            ALMA_JWT_SECRET: j92=8&4i2%3uh2!rhwers7
        depends_on:
            - postgres
            - redis
        ports:
            - '3001:3001'
        volumes:
            - .:/alma
        restart: always

volumes:
    postgres-data:
    redis-data:
